# This is a basic workflow to help you get started with Actions

name: Build ada-lsp

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: List files
      run: ls -al

    # Since there's no Ada environment, I neet to set up one
    # GNAT Community 2018 ships with GNATCOLL, so you will not need to compile it yourself. 
    # However, in this action, there's no community-2018 option. So switch fsf.
    - name: Set up Ada environment
      uses: am1006/toolchain@v0.2.0
      with:
          distrib: community
          target: native
          community_year: 2020

    - name: set up python3 environment
      uses: actions/setup-python@v2
      with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

    - name: Set up homebrew
      run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
          echo "====================="
          brew update

          echo "====================="
          brew install gmp
          
          echo "====================="
          export C_INCLUDE_PATH="/usr/local/Cellar/gmp/6.2.0/include/:$C_INCLUDE_PATH"


    - name: Build GNATCOLL core
      run: |
          git clone https://github.com/AdaCore/gnatcoll-core.git
          cd gnatcoll-core/
          git checkout a2c2-2020
          make setup
          make
          make install

    - name: Build GNATCOLL Bindings
      run: |
          pwd
          git clone https://github.com/AdaCore/gnatcoll-bindings.git
          cd gnatcoll-bindings/
          pwd
          git checkout a2c2-2020
          pwd
          gmp/setup.py build
          gmp/setup.py install
          pwd
          iconv/setup.py build
          iconv/setup.py install

    - name: Build the Libadalang lib
      run: |
          git clone https://github.com/AdaCore/libadalang.git
          cd libadalang/
          pwd
          git checkout a2c2-2020-stable
          virtualenv env
          source env/bin/activate
          pip install -r REQUIREMENTS.dev
          python ada/manage.py generate
          python ada/manage.py build
          python ada/manage.py install ~/Libadalang/

    - name: echo PATH
      run: | 
          export GPR_PROJECT_PATH="~/Libadalang/:$GPR_PROJECT_PATH"
          echo $PATH $GPR_PROJECT_PATH

    # Runs a single command using the runners shell
    - name: Build the ada-lsp binary file
      run: make

    # Upload
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
          name: lsp-server-macos
          path: .obj/server/ada_language_server/
